#!/bin/bash

if ! [[ -f <%= p("rules_path") %> ]]; then
  echo "ERROR: <%= p("rules_path") %> doesn't exist."
  exit 1
fi

if ! grep -e '^-e 2$' <%= p("rules_path") %> -q; then
  cat <<EOF> <%= p("rules_path") %>
# Custom rules; added by auditd job (director-os-conf-release)
<% p("rules").each do |rule| -%>
<%= rule %>
<% end %>
EOF
fi

<% if p("immutable") %>
cat <<EOF>> <%= p("rules_path") %>
# Make audit rules immutable.
-e 2
EOF
<% end %>

systemctl restart auditd